// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which mode the spawned agent runs in.
 */
export type AgentMode = "Plan" | "Implement" | "Fix" | "Restack" | "Review";
