// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How cockpit routes tool-permission requests from a spawned agent.
 *
 * Claude Code runs headlessly (`--print`), where there is no interactive
 * permission prompt: a request that falls outside the auto-allowed set is
 * otherwise denied silently. This setting selects the CLI permission flags
 * applied at spawn time (see
 * [`crate::adapters::agent::SpawnConfig::apply_permission_mode`]).
 *
 * Serializes with PascalCase variant names to match the sibling domain enums.
 */
export type AgentPermissionMode = "Approve" | "AcceptEdits" | "Bypass";
