// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentMode } from "./AgentMode";

/**
 * A running or completed agent process.
 */
export type AgentRun = { 
/**
 * OS process ID of the spawned agent.
 */
pid: number, 
/**
 * Which mode the agent is running in.
 */
mode: AgentMode, 
/**
 * Wall-clock time the agent was spawned.
 *
 * `SystemTime` rather than `Instant` because it must be serializable and
 * meaningful across process boundaries.
 */
started_at: { secs_since_epoch: number; nanos_since_epoch: number }, 
/**
 * Hash of the assembled prompt, for dedup / audit.
 */
prompt_hash: string, 
/**
 * Path to the agent's log file.
 */
log_path: string, };
