// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-[`AgentMode`] custom prompt fragment overrides.
 *
 * Each field holds a user-authored preamble that is injected **verbatim**
 * into the deterministic prompt assembly for that mode (never paraphrased).
 * `None` means "no override": assembly falls back to the builtin intent for
 * that mode. A separate struct (rather than a map) keeps serde/TOML/ts-rs
 * output stable and self-documenting.
 */
export type AgentPrompts = { 
/**
 * Override for [`AgentMode::Implement`].
 */
implement: string | null, 
/**
 * Override for [`AgentMode::Plan`].
 */
plan: string | null, 
/**
 * Override for [`AgentMode::Fix`].
 */
fix: string | null, 
/**
 * Override for [`AgentMode::Restack`].
 */
restack: string | null, 
/**
 * Override for [`AgentMode::Review`].
 */
review: string | null, };
