// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffSide } from "./DiffSide";

/**
 * A location inside the current artifact that a [`Comment`] points to.
 *
 * Anchors are ephemeral — they reference the *current* artifact version only
 * and are cleared together with comments on `Reworked`.
 */
export type Anchor = { "PlanStep": number } | { "PlanFile": string } | { "DiffLine": { 
/**
 * Path relative to the repo root.
 */
path: string, 
/**
 * Inclusive start and end line in the current head.
 */
range: [number, number], 
/**
 * Which side of the diff the range refers to. Defaults to
 * [`DiffSide::New`] for legacy data that predates this field.
 */
side: DiffSide, } };
