// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffData } from "./DiffData";
import type { PlanDoc } from "./PlanDoc";

/**
 * The reviewable artifact — either a plan or a diff.
 *
 * Using an enum makes illegal states unrepresentable: a reviewed object holds
 * exactly one artifact kind, never both or neither.
 */
export type Artifact = { "Plan": PlanDoc } | { "Diff": DiffData };
