// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregate progress of a project's implementer batch after fan-out.
 *
 * Serializable so it can cross the Tauri IPC boundary and drive a progress
 * view. Counts partition the project's reviews by where they are in the loop:
 * a review is `building` while its implementer runs (an agent is attached and
 * it is still `Pending`), `ready` once it is reviewable but not yet
 * approved/merged, and `approved` when the diff gate has passed.
 */
export type BatchStatus = { 
/**
 * Total reviews belonging to the project.
 */
total: number, 
/**
 * Reviews whose implementer agent is still running (`Pending` + agent).
 */
building: number, 
/**
 * Reviews ready for human review but not yet approved.
 */
ready: number, 
/**
 * Reviews whose diff gate has been approved.
 */
approved: number, };
