// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Configurable thresholds for batch-approve heuristics.
 *
 * Controls which reviews are deemed eligible for batch approval.
 * The defaults represent conservative quality gates.
 */
export type BatchApproveConfig = { 
/**
 * Maximum number of files changed in the diff for auto-eligibility.
 *
 * Reviews touching more files than this are flagged for manual review.
 * Set to `0` to disable this check.
 */
max_files_changed: number, };
