// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outcome of evaluating a single review against batch-approve heuristics.
 *
 * Carries human-readable reasons so the user can understand *why* a review
 * is eligible or ineligible.
 */
export type BatchVerdict = { "kind": "Eligible", 
/**
 * Human-readable reasons why this review qualifies.
 */
reasons: Array<string>, } | { "kind": "Ineligible", 
/**
 * Human-readable reasons why this review does not qualify.
 */
reasons: Array<string>, };
