// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single CI check as returned by `gh pr checks --json`.
 *
 * `gh pr checks` reports each check's `bucket` — a normalized rollup of the
 * raw state that groups the many possible GitHub statuses into a handful of
 * outcomes (`pass`, `fail`, `pending`, `skipping`, `cancel`). The bucket is
 * the reliable signal for summarizing pass/fail; `state` is the raw value.
 */
export type CiCheck = { 
/**
 * Name of the check (e.g. "build", "lint").
 */
name: string, 
/**
 * Raw check state (e.g. "SUCCESS", "FAILURE", "PENDING", "SKIPPED").
 */
state: string, 
/**
 * Normalized outcome bucket from `gh` (e.g. "pass", "fail", "pending").
 */
bucket: string, 
/**
 * Deep link to the check run's details page (used to extract the run id).
 */
link: string, 
/**
 * Workflow name the check belongs to, when available.
 */
workflow: string, };
