// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Rollup of a set of [`CiCheck`]s into pass/fail/pending counts.
 *
 * Drives the diff-gate CI badge. Neutral and skipped checks count as passing:
 * they do not indicate a failure and should not block or alarm the reviewer.
 */
export type CiSummary = { 
/**
 * Checks that passed (includes neutral/skipped/cancelled).
 */
passed: number, 
/**
 * Total number of checks.
 */
total: number, 
/**
 * Checks that failed.
 */
failed: number, 
/**
 * Checks still pending (queued or in progress).
 */
pending: number, };
