// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single command an agent ran during its work, paired with its outcome.
 *
 * Defined here in the evidence module so [`EvidenceSummary`] can carry it now;
 * Phase D's trajectory module reuses this type to summarize what an agent
 * executed (there is no separate trajectory module yet).
 */
export type CommandRun = { 
/**
 * The command line the agent ran.
 */
command: string, 
/**
 * Whether the command exited successfully.
 */
ok: boolean, };
