// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Anchor } from "./Anchor";
import type { CommentId } from "./CommentId";
import type { CommentOrigin } from "./CommentOrigin";

/**
 * An ephemeral review comment. Lives for one review -> rework cycle and is
 * cleared on `Reworked`. No `resolved` flag, no durable SHA anchoring
 * (Invariant 4).
 */
export type Comment = { 
/**
 * Locally-unique comment identifier.
 */
id: CommentId, 
/**
 * Where in the artifact this comment points.
 */
anchor: Anchor, 
/**
 * The comment body text.
 */
body: string, 
/**
 * Where the comment came from.
 */
origin: CommentOrigin, };
