// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentPrompts } from "./AgentPrompts";
import type { LspServers } from "./LspServers";
import type { SkillsGithub } from "./SkillsGithub";

/**
 * Persistent application configuration stored at `~/.cockpit/config.toml`.
 *
 * All fields have sensible defaults so the app works out of the box.
 * Optional fields are `None` until the user fills them in through the
 * settings UI. New fields use `#[serde(default)]` for backward
 * compatibility with existing config files.
 */
export type Config = { 
/**
 * Linear personal API key (e.g. `lin_api_...`).
 */
linear_api_key: string | null, 
/**
 * Default Linear project ID to work with.
 */
linear_project_id: string | null, 
/**
 * Path to the git repository managed by cockpit.
 */
repo_path: string | null, 
/**
 * Command used to spawn the agent (default: `"claude"`).
 */
agent_command: string, 
/**
 * Port for the Stop-hook listener (default: `19876`).
 */
hook_port: number, 
/**
 * Maximum number of implementer agents to run concurrently during a
 * plan-approval fan-out (default: `3`).
 *
 * Bounds resource use when a project's frontier is large: `spawn_batch`
 * spawns at most this many agents at once and waits for a slot before
 * starting the next.
 */
max_parallel_agents: number, 
/**
 * Shell command to launch the preferred IDE (e.g. `"cursor"`, `"code"`).
 */
ide_command: string | null, 
/**
 * Application color theme: `"dark"`, `"light"`, or `"system"`.
 */
app_theme: string | null, 
/**
 * Monaco editor theme identifier (default: `"vs-dark"`).
 */
editor_theme: string | null, 
/**
 * Per-[`AgentMode`] custom prompt fragment overrides.
 *
 * Each present override is injected verbatim into the corresponding
 * mode's prompt; absent modes fall back to the builtin intent.
 */
agent_prompts: AgentPrompts, 
/**
 * Optional GitHub source for installable skills.
 *
 * `None` means no remote source is configured; skills are then local-only.
 */
skills_github: SkillsGithub | null, 
/**
 * Language-server command configuration for the Monaco LSP bridge.
 *
 * Controls whether the bridge runs and which binaries back each language.
 */
lsp_servers: LspServers, };
