// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Persistent application configuration stored at `~/.cockpit/config.toml`.
 *
 * All fields have sensible defaults so the app works out of the box.
 * Optional fields (`linear_api_key`, `linear_project_id`, `repo_path`)
 * are `None` until the user fills them in through the settings UI.
 */
export type Config = { 
/**
 * Linear personal API key (e.g. `lin_api_...`).
 */
linear_api_key: string | null, 
/**
 * Default Linear project ID to work with.
 */
linear_project_id: string | null, 
/**
 * Path to the git repository managed by cockpit.
 */
repo_path: string | null, 
/**
 * Command used to spawn the agent (default: `"claude"`).
 */
agent_command: string, 
/**
 * Port for the Stop-hook listener (default: `19876`).
 */
hook_port: number, };
