// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Persistent application configuration stored at `~/.cockpit/config.toml`.
 *
 * All fields have sensible defaults so the app works out of the box.
 * Optional fields are `None` until the user fills them in through the
 * settings UI. New fields use `#[serde(default)]` for backward
 * compatibility with existing config files.
 */
export type Config = { 
/**
 * Linear personal API key (e.g. `lin_api_...`).
 */
linear_api_key: string | null, 
/**
 * Default Linear project ID to work with.
 */
linear_project_id: string | null, 
/**
 * Path to the git repository managed by cockpit.
 */
repo_path: string | null, 
/**
 * Command used to spawn the agent (default: `"claude"`).
 */
agent_command: string, 
/**
 * Port for the Stop-hook listener (default: `19876`).
 */
hook_port: number, 
/**
 * Anthropic API key for direct model access.
 */
anthropic_api_key: string | null, 
/**
 * Model identifier to use for agent runs (default: `"claude-sonnet-4-6"`).
 */
model: string | null, 
/**
 * Optional daily spend cap in US dollars. `None` means unlimited.
 */
daily_budget_usd: number | null, 
/**
 * GitHub personal access token for API operations.
 */
github_token: string | null, 
/**
 * Shell command to launch the preferred IDE (e.g. `"cursor"`, `"code"`).
 */
ide_command: string | null, 
/**
 * Application color theme: `"dark"`, `"light"`, or `"system"`.
 */
app_theme: string | null, 
/**
 * Monaco editor theme identifier (default: `"vs-dark"`).
 */
editor_theme: string | null, 
/**
 * Terminal font family name (default: `"SF Mono"`).
 */
terminal_font: string | null, 
/**
 * Terminal font size in points (default: `13`).
 */
terminal_font_size: number | null, };
