// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kind of GitHub conversation item mirrored into a review for context.
 */
export type ConversationKind = "Review" | "ReviewComment" | "IssueComment";
