// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationKind } from "./ConversationKind";
import type { DiffSide } from "./DiffSide";

/**
 * A read-only GitHub conversation item shown alongside a review for context.
 *
 * This is deliberately **not** a [`Comment`]: it is external context pulled
 * from GitHub, never cleared by the gate on `Reworked`. That §0.4 distinction
 * keeps cockpit's own comments ephemeral while GitHub threads persist.
 */
export type ConversationItem = { 
/**
 * GitHub identifier for this item.
 */
id: string, 
/**
 * Which kind of conversation item this is.
 */
kind: ConversationKind, 
/**
 * Login of the author.
 */
author: string, 
/**
 * The item's body text.
 */
body: string, 
/**
 * Path the item is anchored to, for inline review comments.
 */
path: string | null, 
/**
 * Line the item is anchored to, for inline review comments.
 */
line: number | null, 
/**
 * Which side of the diff the item is anchored to, when inline.
 */
side: DiffSide | null, 
/**
 * Review state (e.g. `"APPROVED"`), for review submissions.
 */
state: string | null, 
/**
 * ISO-8601 creation timestamp as reported by GitHub.
 */
created_at: string, 
/**
 * Permalink to the item on GitHub.
 */
url: string | null, };
