// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Placeholder for parsed diff content.
 *
 * Will be fleshed out when the GitHub adapter (T0.5) and the diff-gate UI
 * (T4.3) need real structure.
 */
export type DiffData = { 
/**
 * Raw unified-diff text.
 */
raw: string, };
