// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RiskPath } from "./RiskPath";
import type { SizeClass } from "./SizeClass";
import type { TestDelta } from "./TestDelta";
import type { WeakeningFlag } from "./WeakeningFlag";

/**
 * The full deterministic signal set for one diff.
 */
export type DiffSignals = { 
/**
 * Total added lines.
 */
additions: number, 
/**
 * Total removed lines.
 */
deletions: number, 
/**
 * Number of files the diff touches (one per `diff --git` header).
 */
files_changed: number, 
/**
 * Size bucket derived from additions + deletions.
 */
size_class: SizeClass, 
/**
 * Test-surface movement.
 */
test_delta: TestDelta, 
/**
 * Risky files, at most one flag per file.
 */
risk_paths: Array<RiskPath>, 
/**
 * Suspected test-weakening flags.
 */
weakening: Array<WeakeningFlag>, };
