// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which side of a diff an [`Anchor::DiffLine`] range refers to.
 *
 * A comment can anchor to the old (pre-change) side or the new (post-change)
 * side of the diff. Defaults to [`DiffSide::New`], matching the common case of
 * commenting on added or changed lines.
 */
export type DiffSide = "Old" | "New";
