// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Comment } from "./Comment";

/**
 * A read-only, single-cycle audit record of what the reviewer asked for at the
 * moment comments were dispatched to an agent.
 *
 * Captured by [`crate::model::Review::snapshot_dispatch`] and overwritten on
 * the next dispatch. This is **not** a durable comment store: comments remain
 * ephemeral and are cleared on `Reworked` (Invariant §0.4). The snapshot exists
 * only so the UI can show "what was asked for" during the in-flight cycle.
 */
export type DispatchSnapshot = { 
/**
 * The review's HEAD SHA at the moment of dispatch.
 */
reviewed_sha: string, 
/**
 * The comments dispatched to the agent this cycle.
 */
comments: Array<Comment>, };
