// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A parsed event from Claude Code's JSONL stream.
 *
 * Each variant carries only the data the UI needs. Large payloads (full
 * file contents in tool inputs) are summarised to keep IPC lightweight.
 */
export type Event = { "kind": "Init", 
/**
 * Model name (e.g. `"claude-opus-4-6"`).
 */
model: string, 
/**
 * Unique session identifier.
 */
session_id: string, 
/**
 * Names of tools available to the agent.
 */
tools: Array<string>, } | { "kind": "Thinking", 
/**
 * Total estimated thinking tokens so far.
 */
estimated_tokens: number, 
/**
 * Tokens added since the last thinking event.
 */
delta: number, } | { "kind": "ToolUse", 
/**
 * Tool-use block id (matches a later [`Event::ToolResult`]).
 */
id: string, 
/**
 * Tool name (e.g. `"Read"`, `"Edit"`, `"Bash"`).
 */
name: string, 
/**
 * One-line summary of the tool input.
 */
input_summary: string, } | { "kind": "ToolResult", 
/**
 * The `tool_use_id` that this result corresponds to.
 */
tool_use_id: string, 
/**
 * Whether the tool succeeded.
 */
success: boolean, 
/**
 * Short summary of the output.
 */
summary: string, } | { "kind": "Text", 
/**
 * The text content.
 */
content: string, } | { "kind": "SubagentSpawn", 
/**
 * Tool-use block id.
 */
id: string, 
/**
 * The prompt or task description sent to the subagent.
 */
prompt: string, } | { "kind": "SubagentResult", 
/**
 * The `tool_use_id` of the spawn that produced this result.
 */
tool_use_id: string, 
/**
 * The subagent's output.
 */
result: string, } | { "kind": "RateLimit", 
/**
 * Human-readable status string.
 */
status: string, } | { "kind": "Complete", 
/**
 * Wall-clock duration in milliseconds.
 */
duration_ms: number, 
/**
 * Total cost in USD.
 */
cost_usd: number, 
/**
 * Number of conversation turns.
 */
num_turns: number, 
/**
 * Total output tokens generated.
 */
output_tokens: number, 
/**
 * The final result text.
 */
result_text: string, } | { "kind": "Error", 
/**
 * Human-readable error message.
 */
message: string, };
