// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CiSummary } from "./CiSummary";
import type { CommandRun } from "./CommandRun";
import type { DiffSignals } from "./DiffSignals";

/**
 * The review-time evidence bundle: deterministic diff signals, the CI rollup,
 * and the commands the agent ran.
 *
 * Assembled per review so the diff gate can show, in one place, what changed
 * (the [`DiffSignals`]), whether CI is green (the [`CiSummary`]), and what the
 * agent actually executed (the [`CommandRun`]s).
 */
export type EvidenceSummary = { 
/**
 * Deterministic diff-derived signals for the review.
 */
signals: DiffSignals, 
/**
 * Rolled-up CI status, when a CI check has populated it.
 */
ci: CiSummary | null, 
/**
 * Commands the agent ran; empty until Phase D fills it from the trajectory.
 */
agent_ran: Array<CommandRun>, };
