// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The full text of a single file on both sides of a review's diff.
 *
 * Feeds the diff gate's optional full-file view (Monaco). `full` is `true` only
 * when the pair was resolved: a side that is legitimately absent (an added or
 * deleted file) is an empty string but still counts as resolved. `full` is
 * `false` when the content could not be determined on either side, signalling
 * the frontend to fall back to the diff fragments.
 */
export type FilePair = { 
/**
 * File text at the base revision (empty when absent on that side).
 */
original: string, 
/**
 * File text at the head revision (empty when absent on that side).
 */
modified: string, 
/**
 * Whether the pair resolved (so the full-file view can be shown).
 */
full: boolean, };
