// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Severity of a [`ReviewFinding`] produced by the advisory pre-pass reviewer.
 */
export type FindingSeverity = "Info" | "Warning" | "Critical";
