// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The shared gate state that drives the review loop for both [`ProjectPlan`]
 * and [`Review`]. See `SPEC.md` §7 for the transition table.
 */
export type GateState = "Pending" | "InReview" | "Dispatched" | "Reworked" | "Approved";
