// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IssueRef } from "./IssueRef";
import type { ProjectPlan } from "./ProjectPlan";
import type { Review } from "./Review";

/**
 * Result of a kickoff operation.
 *
 * Serializable so it can cross the Tauri IPC boundary.
 */
export type KickoffResult = { 
/**
 * The reviews created for each frontier issue.
 */
reviews: Array<Review>, 
/**
 * The project plan, if the plan gate was used.
 */
plan: ProjectPlan | null, 
/**
 * All issues fetched from Linear.
 */
issue_count: number, 
/**
 * The computed frontier (issues ready for work).
 */
frontier: Array<IssueRef>, };
