// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Language-server command configuration for the Monaco LSP bridge.
 *
 * Cockpit does not bundle language servers. The user installs them (for
 * example `npm i -g pyright typescript-language-server`) and cockpit resolves
 * each command via the login-shell `PATH` at spawn time. These fields let a
 * user point at a non-default binary or a wrapper script; when a field is
 * `None`, the built-in default command name is used and looked up on `PATH`.
 */
export type LspServers = { 
/**
 * Whether the Monaco LSP bridge is active at all (default: `true`).
 *
 * When `false`, cockpit never starts a language-server bridge and the
 * diff editor falls back to plain syntax highlighting only.
 */
enabled: boolean, 
/**
 * Override for the Python language-server command
 * (default: `pyright-langserver`).
 *
 * The command is invoked with `--stdio`. `None` uses the default name,
 * resolved on `PATH`.
 */
pyright_command: string | null, 
/**
 * Override for the TypeScript/JavaScript language-server command
 * (default: `typescript-language-server`).
 *
 * The command is invoked with `--stdio`. `None` uses the default name,
 * resolved on `PATH`.
 */
typescript_command: string | null, };
