// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How GitHub should combine a PR's commits when merging.
 *
 * Mirrors `gh pr merge`'s mutually-exclusive strategy flags. Defaults to
 * [`MergeMethod::Squash`], the common single-commit-per-PR workflow.
 */
export type MergeMethod = "Squash" | "Merge" | "Rebase";
