// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentId } from "./CommentId";

/**
 * Result of mirroring local comments to a GitHub PR.
 *
 * Tracks how many comments were successfully posted and collects failures
 * with their reason, so the caller can report partial success.
 */
export type MirrorResult = { 
/**
 * Number of comments successfully posted.
 */
posted: number, 
/**
 * Comments that failed to post: `(comment_id, error_message)`.
 */
failed: Array<[CommentId, string]>, };
