// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single step inside a project plan, used as a comment anchor target.
 */
export type PlanStep = { 
/**
 * Zero-based index in the plan's step list.
 */
index: number, 
/**
 * Human-readable title.
 */
title: string, 
/**
 * Longer description / details.
 */
description: string, };
