// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanStep } from "./PlanStep";

/**
 * Parsed project-plan document. See `SPEC.md` §6.
 */
export type PlanDoc = { 
/**
 * One-line summary of the plan.
 */
summary: string, 
/**
 * Ordered implementation steps.
 */
steps: Array<PlanStep>, 
/**
 * Files the plan intends to touch.
 */
files: Array<string>, 
/**
 * Risks: migrations, new deps, breaking changes.
 */
risks: Array<string>, 
/**
 * The original raw text of the plan.
 */
raw: string, };
