// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectId } from "./ProjectId";
import type { ProjectPlan } from "./ProjectPlan";
import type { ProjectSource } from "./ProjectSource";

/**
 * A first-class project that groups reviews.
 *
 * Reviews may belong to a project (via [`Review::project`]) or be ungrouped
 * (`None`). Linear is one optional [`ProjectSource`], not the entry point.
 */
export type Project = { 
/**
 * Locally-unique project identifier.
 */
id: ProjectId, 
/**
 * Human-readable project name.
 */
name: string, 
/**
 * Where this project came from (Linear or ad-hoc).
 */
source: ProjectSource, 
/**
 * The optional project-level plan reviewed at the plan gate.
 */
plan: ProjectPlan | null, };
