// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRun } from "./AgentRun";
import type { Comment } from "./Comment";
import type { GateState } from "./GateState";
import type { PlanDoc } from "./PlanDoc";
import type { ProjectRef } from "./ProjectRef";

/**
 * The optional project-level plan, reviewed at the plan gate.
 *
 * One per project. When approved, triggers implementation of the full batch.
 */
export type ProjectPlan = { 
/**
 * Which Linear project this plan belongs to.
 */
project: ProjectRef, 
/**
 * The parsed plan document.
 */
doc: PlanDoc, 
/**
 * Current gate state in the review loop.
 */
gate_state: GateState, 
/**
 * Ephemeral comments for the current review cycle.
 */
comments: Array<Comment>, 
/**
 * The agent run responsible for producing / revising the plan.
 */
agent: AgentRun | null, };
