// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Locally-unique identifier for a first-class [`Project`] that groups
 * reviews. Distinct from [`ProjectRef`], which references a Linear project.
 */
export type ProjectId = string;
