// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a first-class [`Project`] came from.
 *
 * Linear is one *optional* source, not the entry point: a project may be
 * created ad-hoc with no Linear backing at all.
 */
export type ProjectSource = { "Linear": string } | "AdHoc";
