// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reference to a GitHub pull request (e.g. `owner/repo#42`).
 */
export type PrRef = string;
