// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRun } from "./AgentRun";
import type { Comment } from "./Comment";
import type { DiffData } from "./DiffData";
import type { GateState } from "./GateState";
import type { IssueRef } from "./IssueRef";
import type { PrRef } from "./PrRef";
import type { ReviewId } from "./ReviewId";

/**
 * A single PR under review at the diff gate.
 *
 * Reviews form a DAG via `parents` / `children`, mirroring the Linear issue
 * dependency graph and the git branch stack.
 */
export type Review = { 
/**
 * Locally-unique review identifier.
 */
id: ReviewId, 
/**
 * The Linear issue this review implements.
 */
issue: IssueRef, 
/**
 * The GitHub PR opened for this review.
 */
pr: PrRef, 
/**
 * Git branch name (e.g. `alejandro/nex-123-do-thing`).
 */
branch: string, 
/**
 * Base branch — either `main` or a parent review's branch (stacked).
 */
base: string, 
/**
 * OID of the base branch tip when this review was created or last restacked.
 *
 * Used as the fork point for `restack`: only commits after this OID belong
 * to this review's branch. Updated after each successful restack.
 */
base_sha: string, 
/**
 * Path to the git worktree on disk.
 */
worktree: string, 
/**
 * Current gate state in the review loop.
 */
gate_state: GateState, 
/**
 * The current diff content.
 */
diff: DiffData, 
/**
 * HEAD commit SHA at last reconcile.
 */
head_sha: string, 
/**
 * Ephemeral comments for the current review cycle.
 */
comments: Array<Comment>, 
/**
 * Ancestor reviews in the stack (from Linear deps).
 */
parents: Array<ReviewId>, 
/**
 * Descendant reviews in the stack.
 */
children: Array<ReviewId>, 
/**
 * An ancestor is in rework; gates deep review but not the loop itself.
 */
stale: boolean, 
/**
 * The agent run responsible for fixing / restacking.
 */
agent: AgentRun | null, };
