// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a [`Review`] originated, determining how comments are handled.
 *
 * `Authored` and `Frontier` reviews dispatch comments to a local agent.
 * `ReviewRequested` reviews mirror comments to GitHub instead.
 */
export type ReviewSource = "Authored" | "ReviewRequested" | "Frontier";
