// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffSide } from "./DiffSide";
import type { FindingSeverity } from "./FindingSeverity";

/**
 * A single advisory finding from the read-only pre-pass reviewer
 * ([`AgentMode::Review`]).
 *
 * Findings annotate the diff for the human reviewer; they never advance the
 * gate and are deliberately not [`Comment`]s.
 */
export type ReviewFinding = { 
/**
 * Stable identifier for this finding within a review cycle.
 */
id: string, 
/**
 * How serious the finding is.
 */
severity: FindingSeverity, 
/**
 * Path relative to the repo root the finding refers to.
 */
path: string, 
/**
 * Inclusive start and end line the finding covers.
 */
range: [number, number], 
/**
 * Which side of the diff the range refers to.
 */
side: DiffSide, 
/**
 * Short one-line summary of the finding.
 */
title: string, 
/**
 * Longer explanation of why this is a finding.
 */
rationale: string, };
