// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRun } from "./AgentRun";
import type { CiSummary } from "./CiSummary";
import type { Comment } from "./Comment";
import type { ConversationItem } from "./ConversationItem";
import type { DiffData } from "./DiffData";
import type { DispatchSnapshot } from "./DispatchSnapshot";
import type { GateState } from "./GateState";
import type { IssueRef } from "./IssueRef";
import type { PrRef } from "./PrRef";
import type { ProjectId } from "./ProjectId";
import type { ReviewFinding } from "./ReviewFinding";
import type { ReviewId } from "./ReviewId";
import type { ReviewSource } from "./ReviewSource";

/**
 * A single PR under review at the diff gate.
 *
 * Reviews form a DAG via `parents` / `children`, mirroring the Linear issue
 * dependency graph and the git branch stack.
 */
export type Review = { 
/**
 * Locally-unique review identifier.
 */
id: ReviewId, 
/**
 * The Linear issue this review implements.
 */
issue: IssueRef, 
/**
 * The GitHub PR opened for this review.
 */
pr: PrRef, 
/**
 * PR title. Empty for legacy data that predates this field.
 */
title: string, 
/**
 * PR description / body. Empty for legacy data that predates this field.
 */
body: string, 
/**
 * Git branch name (e.g. `alejandro/nex-123-do-thing`).
 */
branch: string, 
/**
 * Base branch — either `main` or a parent review's branch (stacked).
 */
base: string, 
/**
 * OID of the base branch tip when this review was created or last restacked.
 *
 * Used as the fork point for `restack`: only commits after this OID belong
 * to this review's branch. Updated after each successful restack.
 */
base_sha: string, 
/**
 * Where this review originated (authored, review request, or frontier).
 */
source: ReviewSource, 
/**
 * Path to the git worktree on disk.
 */
worktree: string, 
/**
 * Current gate state in the review loop.
 */
gate_state: GateState, 
/**
 * The current diff content.
 */
diff: DiffData, 
/**
 * HEAD commit SHA at last reconcile.
 */
head_sha: string, 
/**
 * Ephemeral comments for the current review cycle.
 */
comments: Array<Comment>, 
/**
 * Ancestor reviews in the stack (from Linear deps).
 */
parents: Array<ReviewId>, 
/**
 * Descendant reviews in the stack.
 */
children: Array<ReviewId>, 
/**
 * An ancestor is in rework; gates deep review but not the loop itself.
 */
stale: boolean, 
/**
 * The agent run responsible for fixing / restacking.
 */
agent: AgentRun | null, 
/**
 * GitHub repository slug (e.g. `"owner/repo"`), used for cross-repo
 * operations like fetching diffs via `gh --repo`. `None` for reviews
 * created from the local repo context (kickoff).
 */
repo_slug: string | null, 
/**
 * The first-class [`Project`] this review belongs to, if any. `None` for
 * ungrouped reviews (e.g. GitHub-imported PRs with no project attached).
 */
project: ProjectId | null, 
/**
 * Read-only audit record of the most recent dispatch cycle, if any.
 *
 * Overwritten on each dispatch (see [`DispatchSnapshot`]). `None` before
 * the first dispatch and for legacy data.
 */
dispatch_snapshot: DispatchSnapshot | null, 
/**
 * Rolled-up CI status for this review's PR, when fetched. `None` until a
 * CI check read populates it, and for legacy data that predates the field.
 */
ci_summary: CiSummary | null, 
/**
 * Advisory findings from the read-only pre-pass reviewer, if it has run.
 *
 * Empty by default; never advances the gate (see [`ReviewFinding`]).
 */
review_findings: Array<ReviewFinding>, 
/**
 * Read-only GitHub conversation context mirrored for this review.
 *
 * Empty by default; not [`Comment`]s and never cleared by the gate.
 */
conversation: Array<ConversationItem>, 
/**
 * The SHA the advisory pre-pass reviewer last reviewed, for staleness.
 *
 * `None` before the first pre-pass and for legacy data.
 */
last_reviewed_sha: string | null, };
