// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kind of review to submit to GitHub, matching the API's `event` values.
 */
export type ReviewEvent = "Approve" | "RequestChanges" | "Comment";
