// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RiskFlag } from "./RiskFlag";

/**
 * A single file flagged as risky, paired with the reason.
 */
export type RiskPath = { 
/**
 * Why this path is risky.
 */
flag: RiskFlag, 
/**
 * Repo-relative path of the flagged file.
 */
path: string, };
