// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A category of change that warrants extra reviewer scrutiny.
 */
export type RiskFlag = "Migration" | "Lockfile" | "CiConfig" | "Auth" | "GithubDir" | "Dependency";
