// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coarse size bucket for a diff, by total changed lines (additions +
 * deletions): `S` < 50, `M` < 200, `L` < 600, `Xl` >= 600.
 */
export type SizeClass = "S" | "M" | "L" | "Xl";
