// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a locally-installed skill came from.
 *
 * Recorded in each skill's `.meta.json` sidecar so sync can decide whether a
 * remote update should overwrite a local edit and so the UI can label origin.
 */
export type SkillSource = { "kind": "Local" } | { "kind": "GitHub", 
/**
 * Repository owner (user or org).
 */
owner: string, 
/**
 * Repository name.
 */
repo: string, 
/**
 * The blob SHA of the `SKILL.md` last fetched, for idempotency.
 */
sha: string, };
