// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillSource } from "./SkillSource";

/**
 * A parsed skill definition loaded from a markdown file with YAML frontmatter.
 */
export type Skill = { 
/**
 * Short identifier from frontmatter.
 */
name: string, 
/**
 * One-line description from frontmatter.
 */
description: string, 
/**
 * Optional tags for filtering by relevance (e.g. `["rust", "testing"]`).
 */
tags: Array<string>, 
/**
 * The full markdown body (after frontmatter).
 */
body: string, 
/**
 * Source file path.
 */
path: string, 
/**
 * Provenance of the skill (local vs. GitHub), read from the `.meta.json`
 * sidecar. Defaults to [`SkillSource::Local`] when no sidecar exists so
 * hand-authored skills surface a Local badge in the UI.
 */
source: SkillSource, };
