// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * GitHub source configuration for syncing installable skills.
 *
 * Points at a directory in a repo that holds one skill per subdirectory
 * (`<name>/SKILL.md`). Authentication is the user's existing `gh auth` — there
 * is deliberately no token field here (see PROGRAM_PLAN #3/#8).
 */
export type SkillsGithub = { 
/**
 * Repository owner (user or org).
 */
owner: string, 
/**
 * Repository name.
 */
repo: string, 
/**
 * Branch to sync from (e.g. `"main"`).
 */
branch: string, 
/**
 * Repo-relative path to the directory that holds the skills.
 */
path: string, 
/**
 * Whether cockpit should sync on relevant triggers automatically.
 */
auto_sync: boolean, };
