// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentId } from "./CommentId";

/**
 * Result of submitting a review to a GitHub PR.
 *
 * `submitted` counts the inline comments actually included in the review;
 * `skipped` lists the comments that were left out with a human-readable reason
 * (e.g. their anchored line is not part of the PR's diff), so the caller can
 * report partial success.
 */
export type SubmitReviewResult = { 
/**
 * Number of inline comments included in the submitted review.
 */
submitted: number, 
/**
 * Comments left out of the review: `(comment_id, reason)`.
 */
skipped: Array<[CommentId, string]>, };
