// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outcome counts from a [`sync_from_github`] run.
 *
 * Serializable so the CLI and Tauri surfaces can report progress without
 * re-deriving the numbers.
 */
export type SyncReport = { 
/**
 * Skills newly written (no prior local copy).
 */
installed: number, 
/**
 * Skills whose SHA changed and were overwritten.
 */
updated: number, 
/**
 * Skills skipped because the stored SHA already matched (idempotent).
 */
skipped: number, };
