// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the diff moved the test surface: files touched and assertion churn.
 */
export type TestDelta = { 
/**
 * Number of distinct test files the diff touched.
 */
test_files_changed: number, 
/**
 * Assertion-bearing lines added across the diff.
 */
assertions_added: number, 
/**
 * Assertion-bearing lines removed across the diff.
 */
assertions_removed: number, };
