// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffSide } from "./DiffSide";
import type { WeakeningKind } from "./WeakeningKind";

/**
 * A single suspected test-weakening, with a jump target into the diff.
 *
 * `line`/`side` point at the offending line: the New side for additions
 * (e.g. [`WeakeningKind::IgnoreAdded`]), the Old side for deletions
 * (e.g. [`WeakeningKind::DeletedAssertion`]). File-level flags
 * ([`WeakeningKind::DeletedTestFile`], [`WeakeningKind::SnapshotRewrite`])
 * point at the first removed line.
 */
export type WeakeningFlag = { 
/**
 * What kind of weakening this is.
 */
kind: WeakeningKind, 
/**
 * Repo-relative path of the file.
 */
path: string, 
/**
 * Line number of the offending line on [`Self::side`].
 */
line: number, 
/**
 * Which side of the diff [`Self::line`] refers to.
 */
side: DiffSide, 
/**
 * The trimmed offending line, capped at ~120 characters.
 */
excerpt: string, };
