// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kind of test-weakening a [`WeakeningFlag`] reports.
 */
export type WeakeningKind = "DeletedAssertion" | "IgnoreAdded" | "OrTrue" | "SkipOrTodo" | "DeletedTestFn" | "DeletedTestFile" | "SnapshotRewrite";
